apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: turnbased
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: server
  ports:
    - port: 2567
      targetPort: 2567
      name: http
